[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/users/heramgr/hera_software/hera_opm/pipelines/h1c/idr2/v2/task_scripts"
source_script = "~/.bashrc"
conda_env = "hera3"
base_mem = 64000
base_cpu = 4
timeout = "48h"
pbs_mail_user = "jsdillon+nrao@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = "True"
Nbls_to_load = 150
sigma = 5
min_N = 5
rephase = "True"
ntimes_per_file = 60
dlst = 0.001565970008
lst_start = 0.0
fixed_lst_start = "True"
vis_units = "Jy"
parallelize = "True"
file_ext = "grp1.of2.{type}.{time:7.5f}.HH.OCRSDL.uvh5"
outdir = "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/LSTBIN/two_group/grp1_dly"
parent_dir = "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/LSTBIN/two_group/grp1_dly"
data_files = ["/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458098/zen.2458098.*.HH.OCRSD.uvh5",
             "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458101/zen.2458101.*.HH.OCRSD.uvh5",
             "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458103/zen.2458103.*.HH.OCRSD.uvh5",
             "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458105/zen.2458105.*.HH.OCRSD.uvh5",
             "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458107/zen.2458107.*.HH.OCRSD.uvh5",
             "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458109/zen.2458109.*.HH.OCRSD.uvh5",
             "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458111/zen.2458111.*.HH.OCRSD.uvh5",
             "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458113/zen.2458113.*.HH.OCRSD.uvh5",
             "/lustre/aoc/projects/hera/H1C_IDR2/IDR2_2/2458115/zen.2458115.*.HH.OCRSD.uvh5"]
calibration = "''"

[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "fixed_lst_start", "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "Nbls_to_load", "calibration"]
