[Options]
makeflow_type = "analysis"
# FOR NRAO:
path_to_do_scripts = "/users/jsdillon/Libraries/hera_opm/pipelines/h4c/rtp/v1/stage_1_task_scripts"
conda_env = "python3"
# FOR SITE:
# path_to_do_scripts = "/home/obs/src/hera_opm/pipelines/h4c/rtp/v1/stage_1_task_scripts"
# conda_env = "RTP"
# mandc_report = true
source_script = "~/.bashrc"
base_mem = 16000 # TODO: Check if this is the right number for site
base_cpu = 1
timeout = "24h"

[NOTEBOOK_OPTS]
# FOR NRAO:
nb_template_dir = '/users/jsdillon/Libraries/hera_notebook_templates/notebooks'
nb_output_repo = '/users/jsdillon/Libraries/H4C_Notebooks'
# FOR SITE:
# nb_template_dir = '/home/obs/src/hera_notebook_templates'
# nb_out_dir = '/home/obs/src/H4C_Notebooks'
git_push = false

[ANT_METRICS_OPTS]
crossCut = 5.0
deadCut = 5.0
Nbls_per_load = 100
# TODO: these will need to be updated as commissioning gets underway
# Antennas considered "good" and thus likely candidates for LST-binning
good_statuses = "passed_checks,needs_checking,digital_ok,digital_maintenance,calibration_maintenance,calibration_triage,calibration_ok,dish_maintenance,dish_ok,RF_maintenance,RF_ok"
good_extension = ".known_good.ant_metrics.hdf5"
# Good antennas as well as ntennas that might be ready to promote to "good" status, pending a commissioning meeting.
maybe_statuses = "passed_checks,needs_checking,digital_ok,digital_maintenance,calibration_maintenance,calibration_triage,calibration_ok,dish_maintenance,dish_ok,RF_maintenance,RF_ok"
maybe_extension = ".maybe_good.ant_metrics.hdf5"
# All antennas that are on and worth running ant_metrics and the data_inspect notebook on.
all_statuses = "passed_checks,needs_checking,digital_ok,digital_maintenance,calibration_maintenance,calibration_triage,calibration_ok,dish_maintenance,dish_ok,RF_maintenance,RF_ok"
all_extension = ".all_ants.ant_metrics.hdf5"

[REDCAL_OPTS]
ant_z_thresh = 4
solar_horizon = 0.0
nInt_to_load = 10
flag_nchan_low = 0
flag_nchan_high = 0
oc_maxiter = 5000
min_bl_cut = 15
max_bl_cut = 100

[XRFI_OPTS]
kt_size = 8
kf_size = 8
sig_init = 5.0
sig_adj = 2.0

[XRFI_DAY_THRESHOLD_OPTS]
nsig_f = 7.0
nsig_t = 7.0
nsig_f_adj = 3.0
nsig_t_adj = 3.0

############################################################################################################

[WorkFlow]
actions = ["FIX_DATAFILE", # TODO: REMOVE THIS FOR SITE
           "EXTRACT_AUTOS",
           "ANT_METRICS_KNOWN_GOOD",
           "ANT_METRICS_MAYBE_GOOD",
           "ANT_METRICS_ALL_ANTS",
           "DATA_INSPECT_NOTEBOOK_KNOWN_GOOD",
           "DATA_INSPECT_NOTEBOOK_MAYBE_GOOD",
           "DATA_INSPECT_NOTEBOOK_ALL_ANTS",
           "REDCAL_KNOWN_GOOD",
           "REDCAL_MAYBE_GOOD",
           "REDCAL_INSPECT_NOTEBOOK_KNOWN_GOOD",
           "REDCAL_INSPECT_NOTEBOOK_MAYBE_GOOD",
           "XRFI",
           "XRFI_DAY_THRESHOLD",
           "RFI_INSPECT_NOTEBOOK",
           "DATA_DOWNSELECT", # TODO: THIS DOES NOTHING CURRENTLY
          ]

[FIX_DATAFILE]
args = ["{basename}"]

[EXTRACT_AUTOS]
prereqs = "FIX_DATAFILE"
args = ["{basename}"]

[ANT_METRICS_KNOWN_GOOD]
prereqs = "FIX_DATAFILE"
chunk_size = 10
stride_length = 10
time_centered = false
collect_stragglers = true
args = ["${ANT_METRICS_OPTS:crossCut}",
        "${ANT_METRICS_OPTS:deadCut}",
        "${ANT_METRICS_OPTS:Nbls_per_load}",
        "${ANT_METRICS_OPTS:good_extension}",
        "${ANT_METRICS_OPTS:good_statuses}",
        "{obsid_list}",
       ]

[ANT_METRICS_MAYBE_GOOD]
prereqs = "FIX_DATAFILE"
chunk_size = 10
stride_length = 10
time_centered = false
collect_stragglers = true
args = ["${ANT_METRICS_OPTS:crossCut}",
        "${ANT_METRICS_OPTS:deadCut}",
        "${ANT_METRICS_OPTS:Nbls_per_load}",
        "${ANT_METRICS_OPTS:maybe_extension}",
        "${ANT_METRICS_OPTS:maybe_statuses}",
        "{obsid_list}",
       ]

[ANT_METRICS_ALL_ANTS]
prereqs = "FIX_DATAFILE"
chunk_size = 10
stride_length = 10
time_centered = false
collect_stragglers = true
args = ["${ANT_METRICS_OPTS:crossCut}",
        "${ANT_METRICS_OPTS:deadCut}",
        "${ANT_METRICS_OPTS:Nbls_per_load}",
        "${ANT_METRICS_OPTS:all_extension}",
        "${ANT_METRICS_OPTS:all_statuses}",
        "{obsid_list}",
       ]

[DATA_INSPECT_NOTEBOOK_KNOWN_GOOD]
prereqs = "ANT_METRICS_KNOWN_GOOD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ANT_METRICS_OPTS:good_extension}"
        ]

[DATA_INSPECT_NOTEBOOK_MAYBE_GOOD]
prereqs = "ANT_METRICS_MAYBE_GOOD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ANT_METRICS_OPTS:maybe_extension}"
        ]

[DATA_INSPECT_NOTEBOOK_ALL_ANTS]
prereqs = "ANT_METRICS_ALL_ANTS"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ANT_METRICS_OPTS:all_extension}"
        ]

[REDCAL_KNOWN_GOOD]
prereqs = "ANT_METRICS_KNOWN_GOOD"
args = ["{basename}",
        "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}",
        "${REDCAL_OPTS:flag_nchan_low}",
        "${REDCAL_OPTS:flag_nchan_high}",
        "${REDCAL_OPTS:oc_maxiter}",
        "${REDCAL_OPTS:nInt_to_load}",
        "${REDCAL_OPTS:min_bl_cut}",
        "${REDCAL_OPTS:max_bl_cut}",
        "${ANT_METRICS_OPTS:good_extension}",
       ]

[REDCAL_MAYBE_GOOD]
prereqs = "ANT_METRICS_MAYBE_GOOD"
args = ["{basename}",
        "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}",
        "${REDCAL_OPTS:flag_nchan_low}",
        "${REDCAL_OPTS:flag_nchan_high}",
        "${REDCAL_OPTS:oc_maxiter}",
        "${REDCAL_OPTS:nInt_to_load}",
        "${REDCAL_OPTS:min_bl_cut}",
        "${REDCAL_OPTS:max_bl_cut}",
        "${ANT_METRICS_OPTS:maybe_extension}",
       ]

[REDCAL_INSPECT_NOTEBOOK_KNOWN_GOOD]
prereqs = "REDCAL_KNOWN_GOOD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ANT_METRICS_OPTS:good_extension}"
        ]

[REDCAL_INSPECT_NOTEBOOK_MAYBE_GOOD]
prereqs = "REDCAL_MAYBE_GOOD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ANT_METRICS_OPTS:maybe_extension}"
        ]

[XRFI]
mem = 96000
prereqs = "FIX_DATAFILE"
args = ["${XRFI_OPTS:kt_size}",
        "${XRFI_OPTS:kf_size}",
        "${XRFI_OPTS:sig_init}",
        "${XRFI_OPTS:sig_adj}",
        "{obsid_list}"]
# xrfi will drop data within kt_size of time edge. Total integrations read in
# must be greater than 2 * kt_size. With 2 integrations per file, and kt_size=8,
# chunk_size must be >= 9 (with centered==True).
# Larger chunk_size will reduce redundant i/o and median filter calculation.
# The numbers below result in about 35% redundancy.
# TODO: update these numbers for site
chunk_size = 31
stride_length = 23
time_centered = true
collect_stragglers = true

[XRFI_DAY_THRESHOLD]
prereqs = "XRFI"
args = ["${XRFI_DAY_THRESHOLD_OPTS:nsig_f}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_t}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_f_adj}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_t_adj}",
        "{obsid_list}"
       ]
chunk_size = "all"
stride_length = "all"
time_centered = false

[RFI_INSPECT_NOTEBOOK]
prereqs = "XRFI_DAY_THRESHOLD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        ]

[DATA_DOWNSELECT]
prereqs = "XRFI_DAY_THRESHOLD"
prereq_chunk_size = "all"
args = ["{basename}"]
